#!/bin/sh

set -e

test $DEBIAN_SCRIPT_DEBUG && set -v -x

chperms() {
	# chperms <user> <group> <perms> <file>
	if ! OVERRIDE=`dpkg-statoverride --list $4 2>&1`; then
		if [ -e $4 ]; then
			chown $1:$2 $4
			chmod $3 $4
		fi
	fi
}

case "$1" in
  configure)
    if ! getent passwd boson-meerkat > /dev/null; then
        adduser --system \
                --quiet \
                --group \
                --no-create-home \
                --disabled-password \
                --home /var/lib/boson-meerkat \
                boson-meerkat
    fi

    chperms boson-meerkat boson-meerkat 0775 /var/lib/boson-meerkat
    chperms boson-meerkat boson-meerkat 0775 /var/log/boson-meerkat

    chperms root boson-meerkat 0755 /etc/boson-meerkat
    chperms root boson-meerkat 0644 /etc/boson-meerkat/default.conf

  ;;
esac

# Begin postinst_systemd_enable
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	# This will only remove masks created by d-s-h on package removal.
	deb-systemd-helper unmask 'boson-meerkat.service' >/dev/null || true

	# was-enabled defaults to true, so new installations run enable.
	if deb-systemd-helper --quiet was-enabled 'boson-meerkat.service'; then
		# Enables the unit on first installation, creates new
		# symlinks on upgrades if the unit file has changed.
		deb-systemd-helper enable 'boson-meerkat.service' >/dev/null || true
	else
		# Update the statefile to add new symlinks (if any), which need to be
		# cleaned up on purge. Also remove old symlinks.
		deb-systemd-helper update-state 'boson-meerkat.service' >/dev/null || true
	fi
fi
# End postinst_systemd_enable

# Begin postinst_systemd_start
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -d /run/systemd/system ]; then
		systemctl --system daemon-reload >/dev/null || true
		deb-systemd-invoke start 'boson-meerkat.service' >/dev/null || true
	fi
fi
# End postinst_systemd_start

# Begin postinst_init
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/boson-meerkat" ]; then
		update-rc.d boson-meerkat defaults >/dev/null
		invoke-rc.d boson-meerkat start || exit $?
	fi
fi
# End postinst_init

exit 0;

